extends: '@absolunet/stylelint-config-core'

plugins:
  - stylelint-scss



rules:

  #-- Possible errors

  # Function
  function-calc-no-invalid: null  # conflicts with SCSS variables

  # At-rule
  at-rule-no-unknown: null  # via scss/at-rule-no-unknown

  # Comment
  comment-no-empty: null  # via scss/comment-no-empty



  #-- Limit language features

  # At-rule
  at-rule-disallowed-list:
    - extend
    - message: Unexpected @extend directive (at-rule-disallowed-list)



  #-- Stylistic issues

  # Block
  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
      - if
      - else

  block-opening-brace-space-before:
    - always
    - ignoreAtRules:
      - if
      - else






  #-- Plugins

  #-- Order
  order/order:
    -
      # $variables
      - dollar-variables

      # @include
      - type:     at-rule
        name:     include
        hasBlock: false

      # @include {}
      - type:     at-rule
        name:     include
        hasBlock: true

      # properties
      - declarations

      # Current &,
      - type:     rule
        selector: ^&,
        name:     Parent selector

      # &::pseudo-elements
      - type:     rule
        selector: ^&::[\w-]+,?
        name:     Parent pseudo-elements

      # &:pseudo-classes
      - type:     rule
        selector: ^&:[\w-]+,?
        name:     Parent pseudo-classes
      - type:     rule
        selector: ^#{\$nwayo-hover-selector}$
        name:     Parent pseudo-classes

      # Parent selection &
      - type:     rule
        selector: '&$'
        name:     Parent usage

      # Nested
      - rules

    - unspecified: ignore






  #-- SCSS

  # @-each
  scss/at-each-key-value-single-line: true

  # @-else
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after:   null
  scss/at-else-empty-line-before:           never
  scss/at-else-if-parentheses-space-before: always

  # @-extend
  scss/at-extend-no-missing-placeholder: null  # via at-rule-disallowed-list

  # @-function
  scss/at-function-named-arguments:          null
  scss/at-function-parentheses-space-before: never
  scss/at-function-pattern:
    - ^-?([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - message: Function name must be kebab-case (scss/at-function-pattern)

  # @-if
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after:   null
  scss/at-if-no-null: true

  # @-import
  scss/at-import-no-partial-leading-underscore: true
  scss/at-import-partial-extension:             never
  scss/at-import-partial-extension-blacklist:   null
  scss/at-import-partial-extension-whitelist:         # TODO: Revise css vs scss fallback width Dart
    - scss
    - css

  # @-mixin
  scss/at-mixin-argumentless-call-parentheses: always
  scss/at-mixin-named-arguments:               null
  scss/at-mixin-parentheses-space-before:      never
  scss/at-mixin-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - message: Mixin name must be kebab-case (scss/at-mixin-pattern)

  # @-rule
  scss/at-rule-conditional-no-parentheses: true
  scss/at-rule-no-unknown: true

  # $-variable
  scss/dollar-variable-colon-newline-after:      null
  scss/dollar-variable-colon-space-after:        at-least-one-space
  scss/dollar-variable-colon-space-before:       never
  scss/dollar-variable-default:                  null
  scss/dollar-variable-empty-line-after:         null
  scss/dollar-variable-empty-line-before:        null
  scss/dollar-variable-first-in-block:           null  # via order/order
  scss/dollar-variable-no-missing-interpolation: true
  scss/dollar-variable-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - message: Variable name must be kebab-case (scss/dollar-variable-pattern)

  # %-placeholder
  scss/percent-placeholder-pattern: null  # via at-rule-disallowed-list

  # Comment
  scss/comment-no-empty: true
  scss/comment-no-loud: null

  # //-comment
  scss/double-slash-comment-empty-line-before: null
  scss/double-slash-comment-inline:            null
  scss/double-slash-comment-whitespace-inside: null  # TODO: Reactivate when //-- Supported

  # Declaration
  scss/declaration-nested-properties:                   never
  scss/declaration-nested-properties-no-divided-groups: null   # via scss/declaration-nested-properties

  # Dimension
  scss/dimension-no-non-numeric-values: true

  # Function
  scss/function-color-relative:                     null
  scss/function-quote-no-quoted-strings-inside:     true
  scss/function-unquote-no-unquoted-strings-inside: true

  # Map
  scss/map-keys-quotes: always

  # Media feature
  scss/media-feature-value-dollar-variable: always

  # Operator
  scss/operator-no-newline-after:  true
  scss/operator-no-newline-before: true
  scss/operator-no-unspaced:       true

  # Partial
  scss/partial-no-import: null

  # Selector
  scss/selector-nest-combinators:              null
  scss/selector-no-redundant-nesting-selector: true
  scss/selector-no-union-class-name:           true

  # General / Sheet
  scss/no-dollar-variables:      null
  scss/no-duplicate-dollar-variables:
    - true
    - ignoreInside: at-rule
  scss/no-duplicate-mixins:      true
  scss/no-global-function-names: true
