extends: '@absolunet/stylelint-config-scss'


rules:

  selector-class-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$|^THIS$
    - resolveNestedSelectors: true
      message:                Class selector must be kebab-case or THIS (selector-class-pattern)
